In [1]:
import numpy as np
import cv2

# multiple cascades: https://github.com/Itseez/opencv/tree/master/data/haarcascades

#https://github.com/Itseez/opencv/blob/master/data/haarcascades/haarcascade_frontalface_default.xml
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
#https://github.com/Itseez/opencv/blob/master/data/haarcascades/haarcascade_eye.xml
eye_cascade = cv2.CascadeClassifier('haarcascade_eye.xml')

cap = cv2.VideoCapture(0)

while 1:
    ret, img = cap.read()
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray,1.3, 5)

    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)
        #roi_gray = gray[y:y+h, x:x+w]
        #roi_color = img[y:y+h, x:x+w]
        #eyes = eye_cascade.detectMultiScale(roi_gray)
        #for (ex,ey,ew,eh) in eyes:
            #cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)

    cv2.imshow('img',img)
    k = cv2.waitKey(1)
    if k == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

In [2]:
import cv2,time
video = cv2.VideoCapture(0)
while True:    
    check,frame = video.read()
    print(check)
    print(frame)
    
    #time.sleep(3)
    cv2.imshow("Captured",frame)
    key=cv2.waitKey(1)
    if key==ord('q'):
        break
video.release()
cv2.destroyAllWindows()

True
[[[116  94  32]
  [120  98  35]
  [124 102  40]
  ...
  [107 131 115]
  [112 132 118]
  [113 134 119]]

 [[119  98  38]
  [125 104  44]
  [127 106  48]
  ...
  [110 133 118]
  [108 132 117]
  [108 132 117]]

 [[115  95  34]
  [126 105  45]
  [126 105  45]
  ...
  [111 134 119]
  [107 131 115]
  [106 129 114]]

 ...

 [[ 38  41 107]
  [ 38  41 107]
  [ 41  43 109]
  ...
  [ 66  32 133]
  [ 66  32 133]
  [ 69  34 136]]

 [[ 37  41 104]
  [ 40  43 106]
  [ 41  44 107]
  ...
  [ 65  31 132]
  [ 66  32 133]
  [ 69  34 136]]

 [[ 40  43 106]
  [ 41  44 107]
  [ 41  44 107]
  ...
  [ 68  32 133]
  [ 68  32 133]
  [ 72  35 137]]]
True
[[[114  96  56]
  [120 102  62]
  [124 109  66]
  ...
  [113 125 123]
  [112 127 125]
  [112 127 125]]

 [[115  97  57]
  [120 102  62]
  [122 107  64]
  ...
  [111 126 123]
  [111 126 123]
  [111 126 123]]

 [[117  98  58]
  [117  98  58]
  [121 103  63]
  ...
  [110 125 122]
  [110 125 122]
  [111 126 123]]

 ...

 [[ 43  39 106]
  [ 43  39 106]
  [ 42  39

True
[[[113  98  48]
  [120 105  55]
  [126 110  63]
  ...
  [112 128 121]
  [111 127 120]
  [111 127 120]]

 [[112  97  47]
  [120 105  55]
  [125 112  64]
  ...
  [110 129 121]
  [109 128 120]
  [109 128 120]]

 [[112  97  47]
  [119 104  54]
  [120 107  59]
  ...
  [110 129 121]
  [110 129 121]
  [109 128 120]]

 ...

 [[ 45  39 104]
  [ 45  39 104]
  [ 44  38 103]
  ...
  [ 48  45  80]
  [ 48  46  78]
  [ 48  46  78]]

 [[ 45  39 104]
  [ 44  38 103]
  [ 43  37 102]
  ...
  [ 45  43  77]
  [ 48  46  78]
  [ 49  47  79]]

 [[ 47  39 104]
  [ 47  39 104]
  [ 46  38 103]
  ...
  [ 44  42  76]
  [ 47  45  77]
  [ 49  47  79]]]
True
[[[116 101  37]
  [123 108  44]
  [124 109  46]
  ...
  [114 130 122]
  [114 130 122]
  [112 128 121]]

 [[116 101  37]
  [122 107  43]
  [124 108  47]
  ...
  [112 128 121]
  [112 128 121]
  [112 128 121]]

 [[110  94  33]
  [122 106  45]
  [122 108  49]
  ...
  [111 127 120]
  [111 127 120]
  [111 127 120]]

 ...

 [[ 44  40 107]
  [ 44  40 107]
  [ 46  41

True
[[[118  97  64]
  [121 101  68]
  [120 102  69]
  ...
  [112 128 123]
  [111 127 122]
  [110 125 121]]

 [[117  96  63]
  [122 102  69]
  [122 103  70]
  ...
  [109 128 120]
  [109 128 120]
  [109 128 120]]

 [[110  89  56]
  [125 104  71]
  [122 103  70]
  ...
  [109 128 120]
  [110 129 121]
  [109 128 120]]

 ...

 [[ 44  40 107]
  [ 44  40 107]
  [ 46  41 108]
  ...
  [ 71  68  96]
  [ 75  73 101]
  [ 75  73 101]]

 [[ 45  38 106]
  [ 48  41 108]
  [ 46  40 107]
  ...
  [ 70  67  95]
  [ 75  70  98]
  [ 76  71  99]]

 [[ 46  40 107]
  [ 46  40 107]
  [ 46  40 107]
  ...
  [ 67  65  92]
  [ 70  67  95]
  [ 73  70  98]]]
True
[[[113  96  64]
  [116  99  68]
  [122 105  74]
  ...
  [111 127 120]
  [111 127 120]
  [112 128 121]]

 [[115  96  64]
  [118  99  68]
  [122 105  74]
  ...
  [109 128 120]
  [110 129 121]
  [110 129 121]]

 [[113  94  63]
  [115  96  64]
  [119 100  69]
  ...
  [112 130 122]
  [113 131 124]
  [112 130 122]]

 ...

 [[ 42  37 106]
  [ 44  39 108]
  [ 44  39